namespace :thiennt do
  desc ""
  task run: :environment do
    provinces = [
      "A Lưới,Thừa Thiên-Huế",
      "An Biên,Kiên Giang",
      "An Dương,Hải Phòng",
      "An Khê,Gia Lai",
      "An Lão,Hải Phòng",
      "An Lão,Bình Định",
      "An Minh,Kiên Giang",
      "An Nhơn,Bình Định",
      "An Phú,An Giang",
      "Anh Sơn,Nghệ An",
      "Ayun Pa,Gia Lai",
      "Ân Thi,Hưng Yên",
      "Ba Bể,Bắc Kạn",
      "Ba Chẽ,Quảng Ninh",
      "Ba Đình,Hà Nội",
      "Ba Đồn,Quảng Bình",
      "Ba Tơ,Quảng Ngãi",
      "Ba Tri,Bến Tre",
      "Ba Vì,Hà Nội",
      "Bà Rịa,Bà Rịa-Vũng Tàu",
      "Bá Thước,Thanh Hóa",
      "Bác Ái,Ninh Thuận",
      "Bạc Liêu,Bạc Liêu",
      "Bạch Long Vĩ,Hải Phòng",
      "Bạch Thông,Bắc Kạn",
      "Bảo Lạc,Cao Bằng",
      "Bảo Lâm,Cao Bằng",
      "Bảo Lâm,Lâm Đồng",
      "Bảo Lộc,Lâm Đồng",
      "Bảo Thắng,Lào Cai",
      "Bảo Yên,Lào Cai",
      "Bát Xát,Lào Cai",
      "Bàu Bàng,Bình Dương",
      "Bắc Bình,Bình Thuận",
      "Bắc Giang,Bắc Giang",
      "Bắc Hà,Lào Cai",
      "Bắc Kạn,Bắc Kạn",
      "Bắc Mê,Hà Giang",
      "Bắc Ninh,Bắc Ninh",
      "Bắc Quang,Hà Giang",
      "Bắc Sơn,Lạng Sơn",
      "Bắc Tân Uyên,Bình Dương",
      "Bắc Trà My,Quảng Nam",
      "Bắc Từ Liêm,Hà Nội",
      "Bắc Yên,Sơn La",
      "Bến Cát,Bình Dương",
      "Bến Cầu,Tây Ninh",
      "Bến Lức,Long An",
      "Bến Tre,Bến Tre",
      "Biên Hòa,Đồng Nai",
      "Bỉm Sơn,Thanh Hóa",
      "Bình Chánh,TP Hồ Chí Minh",
      "Bình Đại,Bến Tre",
      "Bình Gia,Lạng Sơn",
      "Bình Giang,Hải Dương",
      "Bình Liêu,Quảng Ninh",
      "Bình Long,Bình Phước",
      "Bình Lục,Hà Nam",
      "Bình Minh,Vĩnh Long",
      "Bình Sơn,Quảng Ngãi",
      "Bình Tân,TP Hồ Chí Minh",
      "Bình Tân,Vĩnh Long",
      "Bình Thạnh,TP Hồ Chí Minh",
      "Bình Thủy,Cần Thơ",
      "Bình Xuyên,Vĩnh Phúc",
      "Bố Trạch,Quảng Bình",
      "Bù Đăng,Bình Phước",
      "Bù Đốp,Bình Phước",
      "Bù Gia Mập,Bình Phước",
      "Buôn Đôn,Đắk Lắk",
      "Buôn Hồ,Đắk Lắk",
      "Buôn Ma Thuột,Đắk Lắk",
      "Cà Mau,Cà Mau",
      "Cai Lậy,Tiền Giang",
      "Cai Lậy,Tiền Giang",
      "Cái Bè,Tiền Giang",
      "Cái Nước,Cà Mau",
      "Cái Răng,Cần Thơ",
      "Cam Lâm,Khánh Hòa",
      "Cam Lộ,Quảng Trị",
      "Cam Ranh,Khánh Hòa",
      "Can Lộc,Hà Tĩnh",
      "Càng Long,Trà Vinh",
      "Cao Bằng,Cao Bằng",
      "Cao Lãnh,Đồng Tháp",
      "Cao Lãnh,Đồng Tháp",
      "Cao Lộc,Lạng Sơn",
      "Cao Phong,Hoà Bình",
      "Cát Hải,Hải Phòng",
      "Cát Tiên,Lâm Đồng",
      "Cẩm Giàng,Hải Dương",
      "Cẩm Khê,Phú Thọ",
      "Cẩm Lệ,Đà Nẵng",
      "Cẩm Mỹ,Đồng Nai",
      "Cẩm Phả,Quảng Ninh",
      "Cẩm Thủy,Thanh Hóa",
      "Cẩm Xuyên,Hà Tĩnh",
      "Cần Đước,Long An",
      "Cần Giờ,TP Hồ Chí Minh",
      "Cần Giuộc,Long An",
      "Cầu Giấy,Hà Nội",
      "Cầu Kè,Trà Vinh",
      "Cầu Ngang,Trà Vinh",
      "Châu Đốc,An Giang",
      "Châu Đức,Bà Rịa-Vũng Tàu",
      "Châu Phú,An Giang",
      "Châu Thành,An Giang",
      "Châu Thành,Bến Tre",
      "Châu Thành,Đồng Tháp",
      "Châu Thành,Hậu Giang",
      "Châu Thành,Kiên Giang",
      "Châu Thành,Long An",
      "Châu Thành,Sóc Trăng",
      "Châu Thành,Tây Ninh",
      "Châu Thành,Tiền Giang",
      "Châu Thành,Trà Vinh",
      "Châu Thành A,Hậu Giang",
      "Chi Lăng,Lạng Sơn",
      "Chí Linh,Hải Dương",
      "Chiêm Hóa,Tuyên Quang",
      "Chợ Đồn,Bắc Kạn",
      "Chợ Gạo,Tiền Giang",
      "Chợ Lách,Bến Tre",
      "Chợ Mới,Bắc Kạn",
      "Chợ Mới,An Giang",
      "Chơn Thành,Bình Phước",
      "Chư Păh,Gia Lai",
      "Chư Prông,Gia Lai",
      "Chư Pưh,Gia Lai",
      "Chư Sê,Gia Lai",
      "Chương Mỹ,Hà Nội",
      "Con Cuông,Nghệ An",
      "Cô Tô,Quảng Ninh",
      "Côn Đảo,Bà Rịa - Vũng Tàu",
      "Cồn Cỏ,Quảng Trị",
      "Cờ Đỏ,Cần Thơ",
      "Cù Lao Dung,Sóc Trăng",
      "Củ Chi,TP Hồ Chí Minh",
      "Cư Kuin,Đắk Lắk",
      "Cư Jút,Đắk Nông",
      "Cư M'gar,Đắk Lắk",
      "Cửa Lò,Nghệ An",
      "Dầu Tiếng,Bình Dương",
      "Di Linh,Lâm Đồng",
      "Dĩ An,Bình Dương",
      "Diên Khánh,Khánh Hòa",
      "Diễn Châu,Nghệ An",
      "Duy Tiên,Hà Nam",
      "Duy Xuyên,Quảng Nam",
      "Duyên Hải,Trà Vinh",
      "Duyên Hải,Trà Vinh",
      "Dương Kinh,Hải Phòng",
      "Dương Minh Châu,Tây Ninh",
      "Đa Krông,Quảng Trị",
      "Đà Bắc,Hoà Bình",
      "Đà Lạt,Lâm Đồng",
      "Đạ Huoai,Lâm Đồng",
      "Đạ Tẻh,Lâm Đồng",
      "Đại Lộc,Quảng Nam",
      "Đại Từ,Thái Nguyên",
      "Đắk Đoa,Gia Lai",
      "Đak Pơ,Gia Lai",
      "Đan Phượng,Hà Nội",
      "Đắk Glei,Kon Tum",
      "Đắk Glong,Đắk Nông",
      "Đắk Hà,Kon Tum",
      "Đắk Mil,Đắk Nông",
      "Đắk R'lấp,Đắk Nông",
      "Đăk Song,Đắk Nông",
      "Đăk Tô,Kon Tum",
      "Đầm Dơi,Cà Mau",
      "Đầm Hà,Quảng Ninh",
      "Đam Rông,Lâm Đồng",
      "Đất Đỏ,Bà Rịa - Vũng Tàu",
      "Điện Bàn,Quảng Nam",
      "Điện Biên,Điện Biên",
      "Điện Biên Đông,Điện Biên",
      "Điện Biên Phủ,Điện Biên",
      "Đình Lập,Lạng Sơn",
      "Định Hóa,Thái Nguyên",
      "Định Quán,Đồng Nai",
      "Đoan Hùng,Phú Thọ",
      "Đô Lương,Nghệ An",
      "Đồ Sơn,Hải Phòng",
      "Đông Anh,Hà Nội",
      "Đông Giang,Quảng Nam",
      "Đông Hà,Quảng Trị",
      "Đông Hải,Bạc Liêu",
      "Đông Hòa,Phú Yên",
      "Đông Hưng,Thái Bình",
      "Đông Sơn,Thanh Hóa",
      "Đông Triều,Quảng Ninh",
      "Đồng Hới,Quảng Bình",
      "Đồng Hỷ,Thái Nguyên",
      "Đồng Phú,Bình Phước",
      "Đồng Văn,Hà Giang",
      "Đồng Xoài,Bình Phước",
      "Đồng Xuân,Phú Yên",
      "Đống Đa,Hà Nội",
      "Đơn Dương,Lâm Đồng",
      "Đức Cơ,Gia Lai",
      "Đức Hòa,Long An",
      "Đức Huệ,Long An",
      "Đức Linh,Bình Thuận",
      "Đức Phổ,Quảng Ngãi",
      "Đức Thọ,Hà Tĩnh",
      "Đức Trọng,Lâm Đồng",
      "Ea H'leo,Đắk Lắk",
      "Ea Kar,Đắk Lắk",
      "Ea Súp,Đắk Lắk",
      "Gia Bình,Bắc Ninh",
      "Gia Lâm,Hà Nội",
      "Gia Lộc,Hải Dương",
      "Gia Nghĩa,Đăk Nông",
      "Gia Viễn,Ninh Bình",
      "Giá Rai,Bạc Liêu",
      "Giang Thành,Kiên Giang",
      "Giao Thủy,Nam Định",
      "Gio Linh,Quảng Trị",
      "Giồng Riềng,Kiên Giang",
      "Giồng Trôm,Bến Tre",
      "Gò Công,Tiền Giang",
      "Gò Công Đông,Tiền Giang",
      "Gò Công Tây,Tiền Giang",
      "Gò Dầu,Tây Ninh",
      "Gò Quao,Kiên Giang",
      "Gò Vấp,TP Hồ Chí Minh",
      "Hà Đông,Hà Nội",
      "Hà Giang,Hà Giang",
      "Hà Quảng,Cao Bằng",
      "Hà Tiên,Kiên Giang",
      "Hà Tĩnh,Hà Tĩnh",
      "Hà Trung,Thanh Hóa",
      "Hạ Hòa,Phú Thọ",
      "Hạ Lang,Cao Bằng",
      "Hạ Long,Quảng Ninh",
      "Hai Bà Trưng,Hà Nội",
      "Hải An,Hải Phòng",
      "Hải Châu,Đà Nẵng",
      "Hải Dương,Hải Dương",
      "Hải Hà,Quảng Ninh",
      "Hải Hậu,Nam Định",
      "Hải Lăng,Quảng Trị",
      "Hàm Tân,Bình Thuận",
      "Hàm Thuận Bắc,Bình Thuận",
      "Hàm Thuận Nam,Bình Thuận",
      "Hàm Yên,Tuyên Quang",
      "Hậu Lộc,Thanh Hóa",
      "Hiệp Đức,Quảng Nam",
      "Hiệp Hòa,Bắc Giang",
      "Hoa Lư,Ninh Bình",
      "Hòa An,Cao Bằng",
      "Hoà Bình,Bạc Liêu",
      "Hoà Bình,Hoà Bình",
      "Hòa Thành,Tây Ninh",
      "Hòa Vang,Đà Nẵng",
      "Hoài Ân,Bình Định",
      "Hoài Đức,Hà Nội",
      "Hoài Nhơn,Bình Định",
      "Hoàn Kiếm,Hà Nội",
      "Hoàng Mai,Hà Nội",
      "Hoàng Mai,Nghệ An",
      "Hoàng Sa,Đà Nẵng",
      "Hoàng Su Phì,Hà Giang",
      "Hoành Bồ,Quảng Ninh",
      "Hoằng Hóa,Thanh Hóa",
      "Hóc Môn,TP Hồ Chí Minh",
      "Hòn Đất,Kiên Giang",
      "Hớn Quản,Bình Phước",
      "Hội An,Quảng Nam",
      "Hồng Bàng,Hải Phòng",
      "Hồng Dân,Bạc Liêu",
      "Hồng Lĩnh,Hà Tĩnh",
      "Hồng Ngự,Đồng Tháp",
      "Hồng Ngự,Đồng Tháp",
      "Huế,Thừa Thiên - Huế",
      "Hưng Hà,Thái Bình",
      "Hưng Nguyên,Nghệ An",
      "Hưng Yên,Hưng Yên",
      "Hương Khê,Hà Tĩnh",
      "Hương Sơn,Hà Tĩnh",
      "Hương Thủy,Thừa Thiên - Huế",
      "Hương Trà,Thừa Thiên - Huế",
      "Hướng Hóa,Quảng Trị",
      "Hữu Lũng,Lạng Sơn",
      "Ia Grai,Gia Lai",
      "Ia H'Drai,Kon Tum",
      "Ia Pa,Gia Lai",
      "K'Bang,Gia Lai",
      "Kế Sách,Sóc Trăng",
      "Khánh Sơn,Khánh Hòa",
      "Khánh Vĩnh,Khánh Hòa",
      "Khoái Châu,Hưng Yên",
      "Kiên Hải,Kiên Giang",
      "Kiên Lương,Kiên Giang",
      "Kiến An,Hải Phòng",
      "Kiến Thụy,Hải Phòng",
      "Kiến Xương,Thái Bình",
      "Kiến Tường,Long An",
      "Kim Bảng,Hà Nam",
      "Kim Bôi,Hoà Bình",
      "Kim Động,Hưng Yên",
      "Kim Sơn,Ninh Bình",
      "Kim Thành,Hải Dương",
      "Kinh Môn,Hải Dương",
      "Kon Plông,Kon Tum",
      "Kon Rẫy,Kon Tum",
      "Kon Tum,Kon Tum",
      "Kông Chro,Gia Lai",
      "Krông Ana,Đắk Lắk",
      "Krông Bông,Đắk Lắk",
      "Krông Búk,Đắk Lắk",
      "Krông Năng,Đắk Lắk",
      "Krông Nô,Đắk Nông",
      "Krông Pa,Gia Lai",
      "Krông Pắk,Đắk Lắk",
      "Kỳ Anh,Hà Tĩnh",
      "Kỳ Anh,Hà Tĩnh",
      "Kỳ Sơn,Hoà Bình",
      "Kỳ Sơn,Nghệ An",
      "La Gi,Bình Thuận",
      "Lạc Dương,Lâm Đồng",
      "Lạc Sơn,Hoà Bình",
      "Lạc Thủy,Hoà Bình",
      "Lai Châu,Lai Châu",
      "Lai Vung,Đồng Tháp",
      "Lang Chánh,Thanh Hóa",
      "Lạng Giang,Bắc Giang",
      "Lạng Sơn,Lạng Sơn",
      "Lào Cai,Lào Cai",
      "Lắk,Đắk Lắk",
      "Lâm Bình,Tuyên Quang",
      "Lâm Hà,Lâm Đồng",
      "Lâm Thao,Phú Thọ",
      "Lấp Vò,Đồng Tháp",
      "Lập Thạch,Vĩnh Phúc",
      "Lê Chân,Hải Phòng",
      "Lệ Thủy,Quảng Bình",
      "Liên Chiểu,Đà Nẵng",
      "Long Biên,Hà Nội",
      "Long Điền,Bà Rịa-Vũng Tàu",
      "Long Hồ,Vĩnh Long",
      "Long Khánh,Đồng Nai",
      "Long Mỹ,Hậu Giang",
      "Long Mỹ,Hậu Giang",
      "Long Phú,Sóc Trăng",
      "Long Thành,Đồng Nai",
      "Long Xuyên,An Giang",
      "Lộc Bình,Lạng Sơn",
      "Lộc Hà,Hà Tĩnh",
      "Lộc Ninh,Bình Phước",
      "Lục Nam,Bắc Giang",
      "Lục Ngạn,Bắc Giang",
      "Lục Yên,Yên Bái",
      "Lương Sơn,Hoà Bình",
      "Lương Tài,Bắc Ninh",
      "Lý Nhân,Hà Nam",
      "Lý Sơn,Quảng Ngãi",
      "Mai Châu,Hoà Bình",
      "Mai Sơn,Sơn La",
      "Mang Thít,Vĩnh Long",
      "Mang Yang,Gia Lai",
      "M'Đrăk,Đắk Lắk",
      "Mèo Vạc,Hà Giang",
      "Mê Linh,Hà Nội",
      "Minh Hóa,Quảng Bình",
      "Minh Long,Quảng Ngãi",
      "Mỏ Cày Bắc,Bến Tre",
      "Mỏ Cày Nam,Bến Tre",
      "Móng Cái,Quảng Ninh",
      "Mộ Đức,Quảng Ngãi",
      "Mộc Châu,Sơn La",
      "Mộc Hóa,Long An",
      "Mù Căng Chải,Yên Bái",
      "Mường Ảng,Điện Biên",
      "Mường Chà,Điện Biên",
      "Mường Khương,Lào Cai",
      "Mường La,Sơn La",
      "Mường Lát,Thanh Hóa",
      "Mường Lay,Điện Biên",
      "Mường Nhé,Điện Biên",
      "Mường Tè,Lai Châu",
      "Mỹ Đức,Hà Nội",
      "Mỹ Hào,Hưng Yên",
      "Mỹ Lộc,Nam Định",
      "Mỹ Tho,Tiền Giang",
      "Mỹ Tú,Sóc Trăng",
      "Mỹ Xuyên,Sóc Trăng",
      "Na Hang,Tuyên Quang",
      "Na Rì,Bắc Kạn",
      "Nam Đàn,Nghệ An",
      "Nam Định,Nam Định",
      "Nam Đông,Thừa Thiên - Huế",
      "Nam Giang,Quảng Nam",
      "Nam Sách,Hải Dương",
      "Nam Trà My,Quảng Nam",
      "Nam Trực,Nam Định",
      "Nam Từ Liêm,Hà Nội",
      "Năm Căn,Cà Mau",
      "Nậm Pồ,Điện Biên",
      "Nậm Nhùn,Lai Châu",
      "Nga Sơn,Thanh Hóa",
      "Ngã Bảy,Hậu Giang",
      "Ngã Năm,Sóc Trăng",
      "Ngân Sơn,Bắc Kạn",
      "Nghi Lộc,Nghệ An",
      "Nghi Xuân,Hà Tĩnh",
      "Nghĩa Đàn,Nghệ An",
      "Nghĩa Hành,Quảng Ngãi",
      "Nghĩa Hưng,Nam Định",
      "Nghĩa Lộ,Yên Bái",
      "Ngọc Hiển,Cà Mau",
      "Ngọc Hồi,Kon Tum",
      "Ngọc Lặc,Thanh Hóa",
      "Ngô Quyền,Hải Phòng",
      "Ngũ Hành Sơn,Đà Nẵng",
      "Nguyên Bình,Cao Bằng",
      "Nha Trang,Khánh Hòa",
      "Nhà Bè,TP Hồ Chí Minh",
      "Nho Quan,Ninh Bình",
      "Nhơn Trạch,Đồng Nai",
      "Như Thanh,Thanh Hóa",
      "Như Xuân,Thanh Hóa",
      "Ninh Bình,Ninh Bình",
      "Ninh Giang,Hải Dương",
      "Ninh Hải,Ninh Thuận",
      "Ninh Hòa,Khánh Hòa",
      "Ninh Kiều,Cần Thơ",
      "Ninh Phước,Ninh Thuận",
      "Ninh Sơn,Ninh Thuận",
      "Nông Cống,Thanh Hóa",
      "Nông Sơn,Quảng Nam",
      "Núi Thành,Quảng Nam",
      "Ô Môn,Cần Thơ",
      "Pác Nặm,Bắc Kạn",
      "Phan Rang-Tháp Chàm,Ninh Thuận",
      "Phan Thiết,Bình Thuận",
      "Phong Điền,Thừa Thiên-Huế",
      "Phong Điền,Cần Thơ",
      "Phong Thổ,Lai Châu",
      "Phổ Yên,Thái Nguyên",
      "Phú Bình,Thái Nguyên",
      "Phú Giáo,Bình Dương",
      "Phú Hòa,Phú Yên",
      "Phú Lộc,Thừa Thiên-Huế",
      "Phú Lương,Thái Nguyên",
      "Phú Mỹ,Bà Rịa - Vũng Tàu",
      "Phú Nhuận,TP Hồ Chí Minh",
      "Phú Ninh,Quảng Nam",
      "Phú Quý,Bình Thuận",
      "Phú Quốc,Kiên Giang",
      "Phú Riềng,Bình Phước",
      "Phú Tân,An Giang",
      "Phú Tân,Cà Mau",
      "Phú Thiện,Gia Lai",
      "Phú Thọ,Phú Thọ",
      "Phú Vang,Thừa Thiên-Huế",
      "Phú Xuyên,Hà Nội",
      "Phù Cát,Bình Định",
      "Phù Cừ,Hưng Yên",
      "Phù Mỹ,Bình Định",
      "Phù Ninh,Phú Thọ",
      "Phù Yên,Sơn La",
      "Phủ Lý,Hà Nam",
      "Phúc Thọ,Hà Nội",
      "Phúc Yên,Vĩnh Phúc",
      "Phục Hòa,Cao Bằng",
      "Phụng Hiệp,Hậu Giang",
      "Phước Long,Bình Phước",
      "Phước Long,Bạc Liêu",
      "Phước Sơn,Quảng Nam",
      "Pleiku,Gia Lai",
      "Quan Hóa,Thanh Hóa",
      "Quan Sơn,Thanh Hóa",
      "Quản Bạ,Hà Giang",
      "Quang Bình,Hà Giang",
      "Quảng Điền,Thừa Thiên-Huế",
      "Quảng Ngãi,Quảng Ngãi",
      "Quảng Ninh,Quảng Bình",
      "Quảng Trạch,Quảng Bình",
      "Quảng Trị,Quảng Trị",
      "Quảng Yên,Quảng Ninh",
      "Quảng Uyên,Cao Bằng",
      "Quảng Xương,Thanh Hóa",
      "Quận 1,TP Hồ Chí Minh",
      "Quận 2,TP Hồ Chí Minh",
      "Quận 3,TP Hồ Chí Minh",
      "Quận 4,TP Hồ Chí Minh",
      "Quận 5,TP Hồ Chí Minh",
      "Quận 6,TP Hồ Chí Minh",
      "Quận 7,TP Hồ Chí Minh",
      "Quận 8,TP Hồ Chí Minh",
      "Quận 9,TP Hồ Chí Minh",
      "Quận 10,TP Hồ Chí Minh",
      "Quận 11,TP Hồ Chí Minh",
      "Quận 12,TP Hồ Chí Minh",
      "Quế Phong,Nghệ An",
      "Quế Sơn,Quảng Nam",
      "Quế Võ,Bắc Ninh",
      "Quy Nhơn,Bình Định",
      "Quốc Oai,Hà Nội",
      "Quỳ Châu,Nghệ An",
      "Quỳ Hợp,Nghệ An",
      "Quỳnh Lưu,Nghệ An",
      "Quỳnh Nhai,Sơn La",
      "Quỳnh Phụ,Thái Bình",
      "Rạch Giá,Kiên Giang",
      "Sa Đéc,Đồng Tháp",
      "Sa Pa,Lào Cai",
      "Sa Thầy,Kon Tum",
      "Sầm Sơn,Thanh Hóa",
      "Si Ma Cai,Lào Cai",
      "Sìn Hồ,Lai Châu",
      "Sóc Sơn,Hà Nội",
      "Sóc Trăng,Sóc Trăng",
      "Sông Cầu,Phú Yên",
      "Sông Công,Thái Nguyên",
      "Sông Hinh,Phú Yên",
      "Sông Lô,Vĩnh Phúc",
      "Sông Mã,Sơn La",
      "Sốp Cộp,Sơn La",
      "Sơn Động,Bắc Giang",
      "Sơn Dương,Tuyên Quang",
      "Sơn Hà,Quảng Ngãi",
      "Sơn Hòa,Phú Yên",
      "Sơn La,Sơn La",
      "Sơn Tây,Hà Nội",
      "Sơn Tây,Quảng Ngãi",
      "Sơn Tịnh,Quảng Ngãi",
      "Sơn Trà,Đà Nẵng",
      "Tam Bình,Vĩnh Long",
      "Tam Dương,Vĩnh Phúc",
      "Tam Đảo,Vĩnh Phúc",
      "Tam Điệp,Ninh Bình",
      "Tam Đường,Lai Châu",
      "Tam Kỳ,Quảng Nam",
      "Tam Nông,Đồng Tháp",
      "Tam Nông,Phú Thọ",
      "Tánh Linh,Bình Thuận",
      "Tân An,Long An",
      "Tân Biên,Tây Ninh",
      "Tân Bình,TP Hồ Chí Minh",
      "Tân Châu,An Giang",
      "Tân Châu,Tây Ninh",
      "Tân Hiệp,Kiên Giang",
      "Tân Hồng,Đồng Tháp",
      "Tân Hưng,Long An",
      "Tân Kỳ,Nghệ An",
      "Tân Lạc,Hoà Bình",
      "Tân Phú,Đồng Nai",
      "Tân Phú,TP Hồ Chí Minh",
      "Tân Phú Đông,Tiền Giang",
      "Tân Phước,Tiền Giang",
      "Tân Sơn,Phú Thọ",
      "Tân Thạnh,Long An",
      "Tân Trụ,Long An",
      "Tân Uyên,Bình Dương",
      "Tân Uyên,Lai Châu",
      "Tân Yên,Bắc Giang",
      "Tây Giang,Quảng Nam",
      "Tây Hòa,Phú Yên",
      "Tây Hồ,Hà Nội",
      "Tây Ninh,Tây Ninh",
      "Tây Sơn,Bình Định",
      "Tây Trà,Quảng Ngãi",
      "Thạch An,Cao Bằng",
      "Thạch Hà,Hà Tĩnh",
      "Thạch Thành,Thanh Hóa",
      "Thạch Thất,Hà Nội",
      "Thái Bình,Thái Bình",
      "Thái Hòa,Nghệ An",
      "Thái Nguyên,Thái Nguyên",
      "Thái Thụy,Thái Bình",
      "Than Uyên,Lai Châu",
      "Thanh Ba,Phú Thọ",
      "Thanh Bình,Đồng Tháp",
      "Thanh Chương,Nghệ An",
      "Thanh Hà,Hải Dương",
      "Thanh Hóa,Thanh Hóa",
      "Thanh Khê,Đà Nẵng",
      "Thanh Liêm,Hà Nam",
      "Thanh Miện,Hải Dương",
      "Thanh Oai,Hà Nội",
      "Thanh Sơn,Phú Thọ",
      "Thanh Thủy,Phú Thọ",
      "Thanh Trì,Hà Nội",
      "Thanh Xuân,Hà Nội",
      "Thạnh Hóa,Long An",
      "Thạnh Phú,Bến Tre",
      "Thạnh Trị,Sóc Trăng",
      "Tháp Mười,Đồng Tháp",
      "Thăng Bình,Quảng Nam",
      "Thiệu Hóa,Thanh Hóa",
      "Thọ Xuân,Thanh Hóa",
      "Thoại Sơn,An Giang",
      "Thông Nông,Cao Bằng",
      "Thống Nhất,Đồng Nai",
      "Thốt Nốt,Cần Thơ",
      "Thới Bình,Cà Mau",
      "Thới Lai,Cần Thơ",
      "Thủ Dầu Một,Bình Dương",
      "Thủ Đức,TP Hồ Chí Minh",
      "Thủ Thừa,Long An",
      "Thuận An,Bình Dương",
      "Thuận Bắc,Ninh Thuận",
      "Thuận Châu,Sơn La",
      "Thuận Nam,Ninh Thuận",
      "Thuận Thành,Bắc Ninh",
      "Thuỷ Nguyên,Hải Phòng",
      "Thường Tín,Hà Nội",
      "Thường Xuân,Thanh Hóa",
      "Tiên Du,Bắc Ninh",
      "Tiền Hải,Thái Bình",
      "Tiên Lãng,Hải Phòng",
      "Tiên Lữ,Hưng Yên",
      "Tiên Phước,Quảng Nam",
      "Tiên Yên,Quảng Ninh",
      "Tiểu Cần,Trà Vinh",
      "Tĩnh Gia,Thanh Hóa",
      "Tịnh Biên,An Giang",
      "Trà Bồng,Quảng Ngãi",
      "Trà Cú,Trà Vinh",
      "Trà Lĩnh,Cao Bằng",
      "Trà Ôn,Vĩnh Long",
      "Trà Vinh,Trà Vinh",
      "Trạm Tấu,Yên Bái",
      "Tràng Định,Lạng Sơn",
      "Trảng Bàng,Tây Ninh",
      "Trảng Bom,Đồng Nai",
      "Trấn Yên,Yên Bái",
      "Trần Đề,Sóc Trăng",
      "Trần Văn Thời,Cà Mau",
      "Tri Tôn,An Giang",
      "Triệu Phong,Quảng Trị",
      "Triệu Sơn,Thanh Hóa",
      "Trùng Khánh,Cao Bằng",
      "Trực Ninh,Nam Định",
      "Trường Sa,Khánh Hòa",
      "Tủa Chùa,Điện Biên",
      "Tuần Giáo,Điện Biên",
      "Tu Mơ Rông,Kon Tum",
      "Tuy An,Phú Yên",
      "Tuy Đức,Đăk Nông",
      "Tuy Hòa,Phú Yên",
      "Tuy Phong,Bình Thuận",
      "Tuy Phước,Bình Định",
      "Tuyên Hóa,Quảng Bình",
      "Tuyên Quang,Tuyên Quang",
      "Tư Nghĩa,Quảng Ngãi",
      "Tứ Kỳ,Hải Dương",
      "Từ Sơn,Bắc Ninh",
      "Tương Dương,Nghệ An",
      "U Minh,Cà Mau",
      "U Minh Thượng,Kiên Giang",
      "Uông Bí,Quảng Ninh",
      "Ứng Hòa,Hà Nội",
      "Vạn Ninh,Khánh Hòa",
      "Văn Bàn,Lào Cai",
      "Văn Chấn,Yên Bái",
      "Văn Giang,Hưng Yên",
      "Văn Lãng,Lạng Sơn",
      "Văn Lâm,Hưng Yên",
      "Văn Quan,Lạng Sơn",
      "Văn Yên,Yên Bái",
      "Vân Canh,Bình Định",
      "Vân Đồn,Quảng Ninh",
      "Vân Hồ,Sơn La",
      "Vị Thanh,Hậu Giang",
      "Vị Thủy,Hậu Giang",
      "Vị Xuyên,Hà Giang",
      "Việt Trì,Phú Thọ",
      "Việt Yên,Bắc Giang",
      "Vinh,Nghệ An",
      "Vĩnh Bảo,Hải Phòng",
      "Vĩnh Châu,Sóc Trăng",
      "Vĩnh Cửu,Đồng Nai",
      "Vĩnh Hưng,Long An",
      "Vĩnh Linh,Quảng Trị",
      "Vĩnh Long,Vĩnh Long",
      "Vĩnh Lộc,Thanh Hóa",
      "Vĩnh Lợi,Bạc Liêu",
      "Vĩnh Thạnh,Bình Định",
      "Vĩnh Thạnh,Cần Thơ",
      "Vĩnh Thuận,Kiên Giang",
      "Vĩnh Tường,Vĩnh Phúc",
      "Vĩnh Yên,Vĩnh Phúc",
      "Võ Nhai,Thái Nguyên",
      "Vũ Quang,Hà Tĩnh",
      "Vũ Thư,Thái Bình",
      "Vụ Bản,Nam Định",
      "Vũng Liêm,Vĩnh Long",
      "Vũng Tàu,Bà Rịa - Vũng Tàu",
      "Xín Mần,Hà Giang",
      "Xuân Lộc,Đồng Nai",
      "Xuân Trường,Nam Định",
      "Xuyên Mộc,Bà Rịa - Vũng Tàu",
      "Ý Yên,Nam Định",
      "Yên Bái,Yên Bái",
      "Yên Bình,Yên Bái",
      "Yên Châu,Sơn La",
      "Yên Dũng,Bắc Giang",
      "Yên Định,Thanh Hóa",
      "Yên Khánh,Ninh Bình",
      "Yên Lạc,Vĩnh Phúc",
      "Yên Lập,Phú Thọ",
      "Yên Minh,Hà Giang",
      "Yên Mô,Ninh Bình",
      "Yên Mỹ,Hưng Yên",
      "Yên Phong,Bắc Ninh",
      "Yên Sơn,Tuyên Quang",
      "Yên Thành,Nghệ An",
      "Yên Thế,Bắc Giang",
      "Yên Thủy,Hoà Bình",
    ]

    key = "AIzaSyAjURU-z8_JVLgBjTmz6Lr7N32hRz5pk3Q"
    # key = "AIzaSyDyahomSzwkUqpRtDj4YB6mBz05OliXmTU"
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?"

    last_run = Thiennt.last
    last_origin_index = last_run&.origin_index
    last_dest_index = last_run&.dest_index

    max_elements = 10
    provinces.each_slice(max_elements).with_index do |origins, origin_index|
      # p [:origin_index, origin_index, :last_origin_index, last_origin_index]
      next if last_origin_index && origin_index < last_origin_index

      origins = origins.join("|")

      provinces.drop(origin_index * max_elements).each_slice(max_elements).with_index do |destinations, dest_index|
        # p [:dest_index, dest_index, :last_dest_index, last_dest_index]
        next if last_dest_index && dest_index <= last_dest_index && origin_index <= last_origin_index

        destinations = destinations.join("|")
        # p [:origin_index, origin_index, :dest_index, dest_index]
        # p [:origins, origins]
        # p [:destinations, destinations]

        query = "origins=#{origins}&destinations=#{destinations}&key=#{key}&language=vi"
        uri = url + query
        path = URI.parse(URI.encode(uri))
        result = HTTParty.get(path)
        data = result.parsed_response

        raise result.body if data["status"] != "OK"

        Thiennt.create(origin_index: origin_index, dest_index: dest_index, data: data)
        sleep 0.5
      end
    end
  end

  desc ""
  task parse: :environment do
    Thiennt.find_in_batches do |batch|
      batch.each do |record|
        # p [:id, record.id, :origin_index, record.origin_index, :dest_index, record.dest_index]
        data = record.data
        dest_addrs = data["destination_addresses"]
        origin_addrs = data["origin_addresses"]
        rows = data["rows"]
        origin_addrs.each_with_index do |origin_addr, origin_index|
          dest_addrs.each_with_index do |dest_addr, dest_index|
            distance = rows[origin_index]["elements"][dest_index]["distance"]
            distance_text = distance&.dig("text")
            distance_value = distance&.dig("value")
            # p [:origin_addr, origin_addr, :dest_addr, dest_addrs[dest_index],
            #    :distance_text, distance_text, :distance_value, distance_value]
            DistanceData.create(origin: origin_addr, dest: dest_addr, distance_text: distance_text, distance_value: distance_value)
          end
        end
      end
    end
  end
end
